name: Build and Deploy
on:
  push:
    branches:
      - main
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Project Depedancies
      run:  npm ci
    - name: Install Gatsby CLI
      run: npm install -g gatsby-cli@2.12.34
    - name: Build
      run: gatsby build
    - name: Verify build
      run: ls -la public
    - name: Upload public dir
      uses: actions/upload-artifact@v2
      with:
        name: public
        path: public
      env:
        CI: true
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Download public dir
      uses: actions/download-artifact@v2
      with:
        name: public
        path: public
    - name: Display structure of downloaded files
      run: ls -R
    - name: SSH and RSync
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --exclude="/dist/, /node_modules/"
        path: public/
        remote_path: ${{ secrets.DESTINATION_PATH }}/${GITHUB_REF##*/}
        remote_host: ${{ secrets.HOST }}
        remote_port: ${{ secrets.SSH_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.SSH_A2_PRIVATE_KEY }}
        remote_key_pass: ${{ secrets.SSH_A2_PRIVATE_KEY_PASS }}

